### ISSUE TITLE
Add tooling to check crate matches hash

### ISSUE THREAD

**Issue by ethanfrey** [confio/cosmwasm-opt#4]
We want to be able to validate the source code behind a repo.

We can now produce the hash deterministically from a local repo, we need to integrate this more with the publishing system:

* Take crate name and version, as well as a claimed wasm hash`. Download them and return error unless hash matches

Follow-up:

* We then need to integrate this script with `wasmcli` to validate a code sample on the blockchain. (TODO: open issue)

**Comment by webmaster128** [comment]
Done in https://github.com/confio/cosmwasm-verify in an (almost) builder agnostic way. For this reason it is in a separate repo.

My current flow is to present the required arguments to the user in the code explorer:

<img width="1212" alt="Bildschirmfoto 2020-02-28 um 16 15 21" src="https://user-images.githubusercontent.com/2603011/75560493-8d6a0400-5a45-11ea-95cd-52257e7675da.png">

It would be trivial to print such a command via the CLI. Closing as done. Let's follow up with more specific tickets.

**Comment by ethanfrey** [comment]
This is very cool
